import { CommonModule } from '@angular/common';
import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Observable, finalize } from 'rxjs';

import { FUNDUS_CONDITION_OPTIONS } from '../../../core/models/phase6a-labels';
import { CostumeItem, Phase6AItemResponse, PropScenographyItem } from '../../../core/models/phase6a.models';
import { CmsListItem, GalleryItemInput } from '../../../core/models/cms.models';
import { MediaSelectionResult, MediaSelectionValue } from '../../../core/models/media.models';
import { AdminNotificationService } from '../../../core/services/admin-notification.service';
import { CmsAdminService } from '../../../core/services/cms-admin.service';
import { Phase6AAdminService } from '../../../core/services/phase6a-admin.service';
import { MediaPickerComponent } from '../../components/media-picker/media-picker.component';
import { RichTextEditorComponent } from '../../components/rich-text-editor/rich-text-editor.component';
import { SeoFieldsComponent } from '../../components/seo-fields/seo-fields.component';
import { StructuredGalleryEditorComponent } from '../../components/structured-gallery-editor/structured-gallery-editor.component';

@Component({selector:'app-admin-fundus-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,MediaPickerComponent,RichTextEditorComponent,SeoFieldsComponent,StructuredGalleryEditorComponent],templateUrl:'./admin-fundus-form.component.html',styleUrl:'./admin-fundus-form.component.scss'})
export class AdminFundusFormComponent implements OnInit {private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly api=inject(Phase6AAdminService);private readonly cms=inject(CmsAdminService);private readonly notifications=inject(AdminNotificationService);readonly kind=signal<'costumes'|'props'>('costumes');readonly itemId=signal('');readonly loading=signal(false);readonly saving=signal(false);readonly error=signal('');readonly mainImage=signal<MediaSelectionValue[]>([]);readonly productions=signal<CmsListItem[]>([]);readonly conditions=FUNDUS_CONDITION_OPTIONS;
  readonly form=this.fb.group({title:['',Validators.required],slug:[''],shortDescription:[''],description:[''],mainImage:[''],galleryItems:this.fb.control<GalleryItemInput[]>([]),inventoryNumber:['',Validators.required],condition:['good',Validators.required],availabilityNote:[''],relatedProduction:[''],status:['draft',Validators.required],publishedAt:[''],isFeatured:[false],displayOrder:[0,[Validators.min(0)]],gender:['unisex'],epoch:[''],size:[''],color:[''],material:[''],itemType:['prop'],category:[''],epochOrStyle:[''],widthCm:this.fb.control<number|null>(null),heightCm:this.fb.control<number|null>(null),depthCm:this.fb.control<number|null>(null),dimensionNote:[''],weight:this.fb.control<number|null>(null,[Validators.min(0)]),seo:this.fb.group({title:[''],description:[''],keywords:this.fb.control<string[]>([]),canonicalUrl:[''],noIndex:[false]})});
  ngOnInit():void{this.kind.set(this.route.snapshot.paramMap.get('kind')==='props'?'props':'costumes');this.itemId.set(this.route.snapshot.paramMap.get('id')||'');this.cms.list<CmsListItem>('productions',{limit:100,status:'published'}).subscribe({next:r=>this.productions.set(r.items)});if(this.itemId())this.load();}
  get isCostume():boolean{return this.kind()==='costumes';}get seo(){return this.form.controls.seo;}hasUnsavedChanges():boolean{return this.form.dirty&&!this.saving();}@HostListener('window:beforeunload',['$event'])beforeUnload(event:BeforeUnloadEvent):void{if(this.hasUnsavedChanges())event.preventDefault();}
  updateImage(selection:MediaSelectionResult):void{this.mainImage.set(selection.items.length?selection.items:selection.ids);this.form.controls.mainImage.setValue(selection.ids[0]||'');this.form.controls.mainImage.markAsDirty();}
  save(status?:'draft'|'published'):void{if(status)this.form.controls.status.setValue(status);if(this.form.invalid||this.saving()){this.form.markAllAsTouched();this.error.set('Naziv i inventarski broj su obavezni.');return;}this.saving.set(true);this.error.set('');const payload=this.payload();const request=(this.itemId()?(this.isCostume?this.api.updateCostume(this.itemId(),payload):this.api.updatePropScenography(this.itemId(),payload)):(this.isCostume?this.api.createCostume(payload):this.api.createPropScenography(payload))) as Observable<Phase6AItemResponse<CostumeItem|PropScenographyItem>>;request.pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.notifications.success('Predmet je sačuvan.');this.patch(r.item);if(!this.itemId()){this.itemId.set(r.item.id);this.router.navigate(['/admin/fundus',this.kind(),r.item.id,'edit'],{replaceUrl:true});}},error:e=>{const message=e?.error?.message||'Čuvanje nije uspelo.';this.error.set(message);this.notifications.error(message);}});}
  preview():void{if(this.itemId())window.open(`/admin/fundus/${this.kind()}/${this.itemId()}/preview`,'_blank','noopener');}
  private load():void{this.loading.set(true);const request=(this.isCostume?this.api.getCostume(this.itemId()):this.api.getPropScenography(this.itemId())) as Observable<Phase6AItemResponse<CostumeItem|PropScenographyItem>>;request.pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.patch(r.item),error:e=>this.error.set(e?.error?.message||'Predmet nije učitan.')});}
  private patch(item:CostumeItem|PropScenographyItem):void{const seo=item.seo||{};const common={title:item.title,slug:item.slug,description:item.description,mainImage:this.mediaId(item.mainImage),galleryItems:(item.galleryItems||[]).map((g,i)=>({media:this.mediaId(g.media),caption:g.caption||'',credit:g.credit||'',altText:g.altText||'',displayOrder:g.displayOrder??i})),inventoryNumber:item.inventoryNumber,condition:item.condition,availabilityNote:item.availabilityNote||'',relatedProduction:typeof item.relatedProduction==='object'?item.relatedProduction?.id||'':'',status:item.status||'draft',publishedAt:this.dateTime(item.publishedAt),isFeatured:item.isFeatured,displayOrder:item.displayOrder,seo:{title:seo.title||'',description:seo.description||'',keywords:seo.keywords||[],canonicalUrl:seo.canonicalUrl||'',noIndex:Boolean(seo.noIndex)}};if('gender'in item)this.form.patchValue({...common,shortDescription:item.shortDescription,gender:item.gender,epoch:item.epoch,size:item.size||'',color:item.color||'',material:item.material||''});else this.form.patchValue({...common,itemType:item.itemType,category:item.category,epochOrStyle:item.epochOrStyle,material:item.material||'',weight:item.weight??null,widthCm:item.dimensions?.widthCm??null,heightCm:item.dimensions?.heightCm??null,depthCm:item.dimensions?.depthCm??null,dimensionNote:item.dimensions?.note||''});const id=this.mediaId(item.mainImage);this.mainImage.set(id?[id]:[]);this.form.markAsPristine();}
  private payload():Record<string,unknown>{const raw=this.form.getRawValue();const base={title:raw.title,slug:raw.slug||undefined,description:raw.description||'',mainImage:raw.mainImage||null,galleryItems:raw.galleryItems||[],inventoryNumber:raw.inventoryNumber,condition:raw.condition,availabilityNote:raw.availabilityNote,relatedProduction:raw.relatedProduction||null,status:raw.status,publishedAt:raw.publishedAt?new Date(raw.publishedAt).toISOString():undefined,isFeatured:raw.isFeatured,displayOrder:Number(raw.displayOrder)||0,seo:raw.seo};return this.isCostume?{...base,shortDescription:raw.shortDescription,gender:raw.gender,epoch:raw.epoch,size:raw.size,color:raw.color,material:raw.material}:{...base,itemType:raw.itemType,category:raw.category,epochOrStyle:raw.epochOrStyle,material:raw.material,weight:raw.weight,dimensions:{widthCm:raw.widthCm,heightCm:raw.heightCm,depthCm:raw.depthCm,note:raw.dimensionNote}};}
  private mediaId(value:unknown):string{if(typeof value==='string')return value;const item=value&&typeof value==='object'?value as Record<string,unknown>:{};return String(item['id']||item['_id']||'');}private dateTime(value?:string):string{if(!value)return'';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
}
