import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Observable, Subject, finalize, takeUntil } from 'rxjs';

import { conditionLabel, contentStatusLabel, costumeGenderLabel, propTypeLabel } from '../../../core/models/phase6a-labels';
import { CostumeItem, Phase6AListResponse, PropScenographyItem } from '../../../core/models/phase6a.models';
import { AdminNotificationService } from '../../../core/services/admin-notification.service';
import { MediaUrlService } from '../../../core/services/media-url.service';
import { Phase6AAdminService } from '../../../core/services/phase6a-admin.service';

@Component({selector:'app-admin-fundus-list',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./admin-fundus-list.component.html',styleUrl:'./admin-fundus-list.component.scss'})
export class AdminFundusListComponent implements OnInit,OnDestroy {private readonly api=inject(Phase6AAdminService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly fb=inject(FormBuilder);private readonly notifications=inject(AdminNotificationService);readonly media=inject(MediaUrlService);private readonly destroy$=new Subject<void>();readonly tab=signal<'costumes'|'props'>('costumes');readonly items=signal<Array<CostumeItem|PropScenographyItem>>([]);readonly loading=signal(false);readonly error=signal('');readonly page=signal(1);readonly pages=signal(1);readonly total=signal(0);readonly filters=this.fb.nonNullable.group({q:[''],status:[''],gender:[''],itemType:[''],condition:['']});
  ngOnInit():void{this.route.queryParamMap.pipe(takeUntil(this.destroy$)).subscribe(params=>{this.tab.set(params.get('tab')==='props'?'props':'costumes');this.page.set(Number(params.get('page'))||1);this.filters.patchValue({q:params.get('q')||'',status:params.get('status')||'',gender:params.get('gender')||'',itemType:params.get('itemType')||'',condition:params.get('condition')||''},{emitEvent:false});this.load();});}ngOnDestroy():void{this.destroy$.next();this.destroy$.complete();}
  setTab(value:'costumes'|'props'):void{this.router.navigate([],{relativeTo:this.route,queryParams:{tab:value==='props'?'props':null,page:null},queryParamsHandling:'merge'});}apply():void{const raw=this.filters.getRawValue();this.router.navigate([],{relativeTo:this.route,queryParams:{q:raw.q||null,status:raw.status||null,gender:this.tab()==='costumes'?raw.gender||null:null,itemType:this.tab()==='props'?raw.itemType||null:null,condition:raw.condition||null,page:null},queryParamsHandling:'merge'});}changePage(value:number):void{if(value<1||value>this.pages())return;this.router.navigate([],{relativeTo:this.route,queryParams:{page:value},queryParamsHandling:'merge'});}id(item:CostumeItem|PropScenographyItem):string{return item.id;}image(item:CostumeItem|PropScenographyItem):string{return this.media.resolve(item.mainImage);}subtitle(item:CostumeItem|PropScenographyItem):string{return 'gender'in item?`${costumeGenderLabel(item.gender)} · ${item.epoch||'Bez epohe'}`:`${propTypeLabel(item.itemType)} · ${item.category||'Bez kategorije'}`;}condition(value:string):string{return conditionLabel(value);}
  status(value?:string):string{return contentStatusLabel(value);}
  publish(item:CostumeItem|PropScenographyItem):void{this.action(this.api.publish(this.resource(),item.id),'Sadržaj je objavljen.');}archive(item:CostumeItem|PropScenographyItem):void{if(window.confirm(`Arhivirati „${item.title}“?`))this.action(this.api.archive(this.resource(),item.id),'Sadržaj je arhiviran.');}remove(item:CostumeItem|PropScenographyItem):void{if(!window.confirm(`Trajno obrisati „${item.title}“?`))return;this.api.remove(this.resource(),item.id).subscribe({next:()=>{this.notifications.success('Sadržaj je obrisan.');this.load();},error:e=>this.notifications.error(e?.error?.message||'Brisanje nije uspelo.')});}
  private load():void{this.loading.set(true);this.error.set('');const raw=this.filters.getRawValue();const query={...raw,page:this.page(),limit:20};const request=(this.tab()==='costumes'?this.api.listCostumes(query):this.api.listPropsScenography(query)) as Observable<Phase6AListResponse<CostumeItem|PropScenographyItem>>;request.pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.items.set(r.items);this.total.set(r.total);this.pages.set(r.totalPages||1);},error:e=>this.error.set(e?.error?.message||'Fundus nije učitan.')});}private resource():string{return this.tab()==='costumes'?'fundus/costumes':'fundus/props-scenography';}private action(request:ReturnType<Phase6AAdminService['publish']>,message:string):void{request.subscribe({next:()=>{this.notifications.success(message);this.load();},error:e=>this.notifications.error(e?.error?.message||'Akcija nije uspela.')});}}
