import { CommonModule } from '@angular/common';
import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CmsOption, GalleryItemInput } from '../../../core/models/cms.models';
import { contentStatusLabel, productionTypeLabel } from '../../../core/models/cms-labels';
import { MediaSelectionResult, MediaSelectionValue } from '../../../core/models/media.models';
import { CmsAdminService } from '../../../core/services/cms-admin.service';
import { AdminNotificationService } from '../../../core/services/admin-notification.service';
import { AdminContentLanguage, AdminLanguageTabsComponent } from '../../components/admin-language-tabs.component';
import { ExternalLinksEditorComponent } from '../../components/external-links-editor/external-links-editor.component';
import { MediaPickerComponent } from '../../components/media-picker/media-picker.component';
import { RichTextEditorComponent } from '../../components/rich-text-editor/rich-text-editor.component';
import { SearchPickerComponent } from '../../components/search-picker/search-picker.component';
import { SeoFieldsComponent } from '../../components/seo-fields/seo-fields.component';
import { StructuredGalleryEditorComponent } from '../../components/structured-gallery-editor/structured-gallery-editor.component';

@Component({selector:'app-admin-news-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AdminLanguageTabsComponent,MediaPickerComponent,RichTextEditorComponent,StructuredGalleryEditorComponent,ExternalLinksEditorComponent,SearchPickerComponent,SeoFieldsComponent],templateUrl:'./admin-news-form.component.html',styleUrl:'./admin-news-form.component.scss'})
export class AdminNewsFormComponent implements OnInit{
  private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly cms=inject(CmsAdminService);private readonly notifications=inject(AdminNotificationService);
  readonly itemId=signal<string|null>(null);readonly isLoading=signal(false);readonly isSaving=signal(false);readonly errorMessage=signal('');readonly imageSelection=signal<MediaSelectionValue[]>([]);readonly attachmentSelection=signal<MediaSelectionValue[]>([]);readonly statuses=signal<Array<{value:string;label:string}>>([]);readonly categories=signal<Array<{value:string;label:string}>>([]);readonly productions=signal<CmsOption[]>([]);readonly activeLanguage=signal<AdminContentLanguage>('sr');
  private originalSlug='';private originalStatus='draft';
  readonly form=this.fb.group({title:['',Validators.required],slug:[''],subtitle:[''],excerpt:[''],body:[''],category:['vest',Validators.required],image:[''],galleryItems:this.fb.control<GalleryItemInput[]>([]),attachment:[''],relatedProduction:[''],externalLinks:this.fb.array<FormGroup>([]),publishedAt:[''],status:['draft',Validators.required],isFeatured:[false],seo:this.fb.group({title:[''],description:[''],keywords:this.fb.control<string[]>([]),canonicalUrl:[''],noIndex:[false]}),translations:this.fb.group({en:this.fb.group({title:[''],slug:[''],subtitle:[''],excerpt:[''],body:[''],categoryLabel:[''],attachmentLabel:[''],seoTitle:[''],seoDescription:['']})})});
  ngOnInit():void{const id=this.route.snapshot.paramMap.get('id');this.itemId.set(id);this.loadOptions();if(id)this.loadNews(id);}
  statusLabel(value:string|undefined|null):string{return contentStatusLabel(value||undefined);}
  get links():FormArray{return this.form.controls.externalLinks;}get seo():FormGroup{return this.form.controls.seo;}get english():FormGroup{return this.form.controls.translations.controls.en;}get isEditMode():boolean{return Boolean(this.itemId());}englishComplete():boolean{const value=this.form.controls.translations.controls.en.getRawValue();return Boolean(value.title?.trim()&&value.slug?.trim()&&value.excerpt?.trim());}
  hasUnsavedChanges():boolean{return this.form.dirty&&!this.isSaving();}@HostListener('window:beforeunload',['$event']) beforeUnload(event:BeforeUnloadEvent):void{if(this.hasUnsavedChanges())event.preventDefault();}
  loadOptions():void{this.cms.formOptions('news').subscribe({next:({options})=>{this.statuses.set(this.pairs(options['statuses']));this.categories.set(this.pairs(options['categories']));this.productions.set(this.array(options['productions']).map((item)=>({id:this.idOf(item),label:String(item['title']||''),meta:`${productionTypeLabel(String(item['type']||''))} / ${contentStatusLabel(String(item['status']||''))}`})));},error:()=>this.errorMessage.set('Opcije forme nisu ucitane.')});}
  loadNews(id:string):void{this.isLoading.set(true);this.cms.get<Record<string,unknown>>('news',id).subscribe({next:({item})=>this.patch(item),error:(error)=>this.errorMessage.set(error?.error?.message||'Vest nije ucitana.'),complete:()=>this.isLoading.set(false)});}
  patch(item:Record<string,unknown>):void{this.originalSlug=String(item['slug']||'');this.originalStatus=String(item['status']||'draft');const seo=this.object(item['seo']);const english=this.object(this.object(item['translations'])['en']);this.form.patchValue({title:String(item['title']||''),slug:this.originalSlug,subtitle:String(item['subtitle']||''),excerpt:String(item['excerpt']||''),body:String(item['body']||''),category:String(item['category']||'vest'),image:this.idOf(item['image']),galleryItems:this.gallery(item),attachment:this.idOf(item['attachment']),relatedProduction:this.idOf(item['relatedProduction']),publishedAt:this.dateTime(item['publishedAt']),status:this.originalStatus,isFeatured:Boolean(item['isFeatured']),seo:{title:String(seo['title']||''),description:String(seo['description']||''),keywords:this.strings(seo['keywords']),canonicalUrl:String(seo['canonicalUrl']||''),noIndex:Boolean(seo['noIndex'])},translations:{en:{title:String(english['title']||''),slug:String(english['slug']||''),subtitle:String(english['subtitle']||''),excerpt:String(english['excerpt']||''),body:String(english['body']||''),categoryLabel:String(english['categoryLabel']||''),attachmentLabel:String(english['attachmentLabel']||''),seoTitle:String(english['seoTitle']||''),seoDescription:String(english['seoDescription']||'')}}});this.imageSelection.set(item['image']?[item['image'] as MediaSelectionValue]:[]);this.attachmentSelection.set(item['attachment']?[item['attachment'] as MediaSelectionValue]:[]);this.links.clear();this.array(item['externalLinks']).forEach((entry,index)=>this.links.push(this.linkGroup(entry,index)));this.form.markAsPristine();}
  save(status?:'draft'|'published'):void{if(status)this.form.controls.status.setValue(status);if(this.form.invalid||this.isSaving()){this.form.markAllAsTouched();this.errorMessage.set('Proverite obavezna polja i linkove.');return;}const slug=this.form.controls.slug.value||'';if(this.originalStatus==='published'&&this.originalSlug&&slug&&slug!==this.originalSlug&&!window.confirm('Promena sluga moze prekinuti postojece linkove. Nastaviti?'))return;this.isSaving.set(true);this.errorMessage.set('');const id=this.itemId();const request=id?this.cms.update<Record<string,unknown>>('news',id,this.payload()):this.cms.create<Record<string,unknown>>('news',this.payload());request.subscribe({next:({item})=>{this.notifications.success('Vest je sacuvana.');this.form.markAsPristine();const saved=this.idOf(item);if(!id&&saved)this.router.navigate(['/admin/news',saved,'edit']);else this.patch(item);},error:(error)=>{const message=error?.error?.message||'Cuvanje nije uspelo.';this.errorMessage.set(message);this.notifications.error(message);},complete:()=>this.isSaving.set(false)});}
  preview():void{const id=this.itemId();if(!id){this.notifications.info('Prvo sacuvajte nacrt.');return;}window.open(`/admin/news/${id}/preview?lang=${this.activeLanguage()}`,'_blank','noopener');}
  updateImage(selection:MediaSelectionResult):void{this.imageSelection.set(selection.items.length?selection.items:selection.ids);this.form.controls.image.setValue(selection.ids[0]||'');this.form.controls.image.markAsDirty();}updateAttachment(selection:MediaSelectionResult):void{this.attachmentSelection.set(selection.items.length?selection.items:selection.ids);this.form.controls.attachment.setValue(selection.ids[0]||'');this.form.controls.attachment.markAsDirty();}
  private payload():Record<string,unknown>{const raw=this.form.getRawValue();return{...raw,image:raw.image||null,attachment:raw.attachment||null,relatedProduction:raw.relatedProduction||null,publishedAt:raw.publishedAt?new Date(raw.publishedAt).toISOString():undefined,galleryItems:(raw.galleryItems||[]).map((item,index)=>({...item,media:this.idOf(item.media),displayOrder:index})),externalLinks:this.array(raw.externalLinks).filter((item)=>item['label']&&item['url']).map((item,index)=>({...item,type:'other',displayOrder:index}))};}
  private linkGroup(value:Record<string,unknown>,index:number){const en=this.object(this.object(value['translations'])['en']);return this.fb.group({label:[String(value['label']||''),Validators.required],url:[String(value['url']||''),[Validators.required,Validators.pattern(/^https?:\/\//i)]],type:['other'],translations:this.fb.group({en:this.fb.group({label:[String(en['label']||'')]})}),displayOrder:[index]});}
  private gallery(item:Record<string,unknown>):GalleryItemInput[]{const values=this.array(item['galleryItems']);if(values.length)return values.map((entry,index)=>({media:entry['media'] as unknown as MediaSelectionValue,caption:String(entry['caption']||''),credit:String(entry['credit']||''),altText:String(entry['altText']||''),translations:this.object(entry['translations']) as GalleryItemInput['translations'],displayOrder:Number(entry['displayOrder']??index)}));return this.array(item['gallery']).map((media,index)=>({media:media as unknown as MediaSelectionValue,caption:'',credit:'',altText:'',displayOrder:index}));}
  private pairs(value:unknown):Array<{value:string;label:string}>{return this.array(value).map((item)=>({value:String(item['value']||''),label:String(item['label']||item['value']||'')}));}private idOf(value:unknown):string{if(!value)return'';if(typeof value==='string')return value;const item=this.object(value);return String(item['_id']||item['id']||'');}private object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};}private array(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.map((item)=>this.object(item)):[];}private strings(value:unknown):string[]{return Array.isArray(value)?value.map(String):[];}private dateTime(value:unknown):string{if(!value)return'';const date=new Date(String(value));const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
}
