import { CommonModule } from '@angular/common';
import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CmsAdminService } from '../../../core/services/cms-admin.service';
import { AdminNotificationService } from '../../../core/services/admin-notification.service';
import { AboutSectionsEditorComponent, buildAboutSection } from '../../components/about-sections-editor/about-sections-editor.component';
import { SeoFieldsComponent } from '../../components/seo-fields/seo-fields.component';

@Component({selector:'app-admin-about-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AboutSectionsEditorComponent,SeoFieldsComponent],templateUrl:'./admin-about-form.component.html',styleUrl:'./admin-about-form.component.scss'})
export class AdminAboutFormComponent implements OnInit{
  private readonly fb=inject(FormBuilder);private readonly cms=inject(CmsAdminService);private readonly notifications=inject(AdminNotificationService);readonly loading=signal(false);readonly saving=signal(false);readonly error=signal('');readonly statuses=[['draft','Nacrt'],['published','Objavljeno'],['archived','Arhivirano']];
  readonly form=this.fb.group({title:['O nama',Validators.required],slug:['o-nama',Validators.required],status:['draft',Validators.required],publishedAt:[''],sections:this.fb.array<FormGroup>([]),seo:this.fb.group({title:[''],description:[''],keywords:this.fb.control<string[]>([]),canonicalUrl:[''],noIndex:[false]})});
  ngOnInit():void{this.load();}get sections(){return this.form.controls.sections;}get seo():FormGroup{return this.form.controls.seo;}hasUnsavedChanges():boolean{return this.form.dirty&&!this.saving();}@HostListener('window:beforeunload',['$event']) beforeUnload(event:BeforeUnloadEvent):void{if(this.hasUnsavedChanges())event.preventDefault();}
  load():void{this.loading.set(true);this.error.set('');this.cms.getStructuredPage<Record<string,unknown>>('about').subscribe({next:({item})=>this.patch(item),error:(error)=>this.error.set(error?.error?.message||'About strana nije ucitana.'),complete:()=>this.loading.set(false)});}
  patch(item:Record<string,unknown>):void{const seo=this.obj(item['seo']);this.form.patchValue({title:String(item['title']||'O nama'),slug:String(item['slug']||'o-nama'),status:String(item['status']||'draft'),publishedAt:this.dateTime(item['publishedAt']),seo:{title:String(seo['title']||''),description:String(seo['description']||''),keywords:Array.isArray(seo['keywords'])?seo['keywords'].map(String):[],canonicalUrl:String(seo['canonicalUrl']||''),noIndex:Boolean(seo['noIndex'])}});this.sections.clear();this.objects(item['sections']).forEach((section,index)=>this.sections.push(buildAboutSection(this.fb,section,index)));this.form.markAsPristine();}
  save(status?:'draft'|'published'):void{if(status)this.form.controls.status.setValue(status);if(this.form.invalid||this.saving()){this.form.markAllAsTouched();this.error.set('Proverite obavezna polja u sekcijama.');return;}this.saving.set(true);this.cms.updateStructuredPage<Record<string,unknown>>('about',this.payload()).subscribe({next:({item})=>{this.notifications.success('About strana je sacuvana.');this.patch(item);},error:(error)=>{const message=error?.error?.message||'Cuvanje nije uspelo.';this.error.set(message);this.notifications.error(message);},complete:()=>this.saving.set(false)});}
  preview():void{window.open('/admin/pages/about/preview','_blank','noopener');}
  private payload():Record<string,unknown>{const raw=this.form.getRawValue();return{...raw,pageType:'about',publishedAt:raw.publishedAt?new Date(raw.publishedAt).toISOString():undefined,sections:this.objects(raw.sections).map((section,index)=>({...section,image:section['image']||null,backgroundImage:section['backgroundImage']||null,displayOrder:index,timelineItems:this.objects(section['timelineItems']).map((item,itemIndex)=>({...item,image:item['image']||null,displayOrder:itemIndex})),featureItems:this.objects(section['featureItems']).map((item,itemIndex)=>({...item,image:item['image']||null,displayOrder:itemIndex})),galleryItems:this.objects(section['galleryItems']).map((item,itemIndex)=>({...item,media:this.id(item['media']),displayOrder:itemIndex}))}))};}
  private id(value:unknown):string{if(typeof value==='string')return value;const item=this.obj(value);return String(item['_id']||item['id']||'');}private obj(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};}private objects(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.map((item)=>this.obj(item)):[];}private dateTime(value:unknown):string{if(!value)return'';const date=new Date(String(value));const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
}
