import { CommonModule } from '@angular/common';
import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

import { GalleryItemInput } from '../../../core/models/cms.models';
import { contentStatusLabel } from '../../../core/models/cms-labels';
import { MediaSelectionResult, MediaSelectionValue } from '../../../core/models/media.models';
import { CmsAdminService } from '../../../core/services/cms-admin.service';
import { AdminNotificationService } from '../../../core/services/admin-notification.service';
import { AdminContentLanguage, AdminLanguageTabsComponent } from '../../components/admin-language-tabs.component';
import { ExternalLinksEditorComponent } from '../../components/external-links-editor/external-links-editor.component';
import { MediaPickerComponent } from '../../components/media-picker/media-picker.component';
import { RichTextEditorComponent } from '../../components/rich-text-editor/rich-text-editor.component';
import { SeoFieldsComponent } from '../../components/seo-fields/seo-fields.component';
import { StructuredGalleryEditorComponent } from '../../components/structured-gallery-editor/structured-gallery-editor.component';
import { TagEditorComponent } from '../../components/tag-editor/tag-editor.component';

@Component({ selector:'app-admin-artist-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AdminLanguageTabsComponent,MediaPickerComponent,RichTextEditorComponent,StructuredGalleryEditorComponent,TagEditorComponent,ExternalLinksEditorComponent,SeoFieldsComponent],templateUrl:'./admin-artist-form.component.html',styleUrl:'./admin-artist-form.component.scss' })
export class AdminArtistFormComponent implements OnInit{
  private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly cms=inject(CmsAdminService);private readonly notifications=inject(AdminNotificationService);
  readonly itemId=signal<string|null>(null);readonly isLoading=signal(false);readonly isSaving=signal(false);readonly errorMessage=signal('');readonly imageSelection=signal<MediaSelectionValue[]>([]);readonly statuses=signal<Array<{value:string;label:string}>>([]);readonly linkTypes=signal<Array<{value:string;label:string}>>([]);readonly activeLanguage=signal<AdminContentLanguage>('sr');
  private originalSlug='';private originalStatus='draft';
  readonly form=this.fb.group({displayName:['',Validators.required],slug:[''],professions:this.fb.control<string[]>([]),biography:[''],image:[''],galleryItems:this.fb.control<GalleryItemInput[]>([]),status:['draft',Validators.required],publishedAt:[''],links:this.fb.array<FormGroup>([]),seo:this.fb.group({title:[''],description:[''],keywords:this.fb.control<string[]>([]),canonicalUrl:[''],noIndex:[false]}),translations:this.fb.group({en:this.fb.group({displayName:[''],slug:[''],professions:this.fb.control<string[]>([]),biography:[''],seoTitle:[''],seoDescription:['']})})});
  ngOnInit():void{const id=this.route.snapshot.paramMap.get('id');this.itemId.set(id);this.loadOptions();if(id)this.loadArtist(id);}
  statusLabel(value:string|undefined|null):string{return contentStatusLabel(value||undefined);}
  get isEditMode():boolean{return Boolean(this.itemId());}get links():FormArray{return this.form.controls.links;}get seo():FormGroup{return this.form.controls.seo;}get english():FormGroup{return this.form.controls.translations.controls.en;}englishComplete():boolean{const value=this.form.controls.translations.controls.en.getRawValue();return Boolean(value.displayName?.trim()&&value.slug?.trim());}
  hasUnsavedChanges():boolean{return this.form.dirty&&!this.isSaving();}@HostListener('window:beforeunload',['$event']) beforeUnload(event:BeforeUnloadEvent):void{if(this.hasUnsavedChanges())event.preventDefault();}
  loadOptions():void{this.cms.formOptions('artist').subscribe({next:({options})=>{this.statuses.set(this.pairs(options['statuses']));this.linkTypes.set(this.pairs(options['linkTypes']));},error:()=>this.errorMessage.set('Opcije forme nisu ucitane.')});}
  loadArtist(id:string):void{this.isLoading.set(true);this.errorMessage.set('');this.cms.get<Record<string,unknown>>('artists',id).subscribe({next:({item})=>this.patchArtist(item),error:(error)=>this.errorMessage.set(error?.error?.message||'Umetnik nije ucitan.'),complete:()=>this.isLoading.set(false)});}
  patchArtist(item:Record<string,unknown>):void{this.originalSlug=String(item['slug']||'');this.originalStatus=String(item['status']||'draft');const seo=this.object(item['seo']);const english=this.object(this.object(item['translations'])['en']);this.form.patchValue({displayName:String(item['displayName']||''),slug:this.originalSlug,professions:this.strings(item['professions']),biography:String(item['biography']||''),image:this.idOf(item['image']),galleryItems:this.galleryValue(item),status:this.originalStatus,publishedAt:this.dateTime(item['publishedAt']),seo:{title:String(seo['title']||''),description:String(seo['description']||''),keywords:this.strings(seo['keywords']),canonicalUrl:String(seo['canonicalUrl']||''),noIndex:Boolean(seo['noIndex'])},translations:{en:{displayName:String(english['displayName']||''),slug:String(english['slug']||''),professions:this.strings(english['professions']),biography:String(english['biography']||''),seoTitle:String(english['seoTitle']||''),seoDescription:String(english['seoDescription']||'')}}});this.imageSelection.set(item['image']?[item['image'] as MediaSelectionValue]:[]);this.links.clear();this.array(item['links']).forEach((entry,index)=>this.links.push(this.linkGroup(entry,index)));this.form.markAsPristine();}
  save(status?:'draft'|'published'):void{if(status)this.form.controls.status.setValue(status);if(this.form.invalid||this.isSaving()){this.form.markAllAsTouched();this.errorMessage.set('Proverite obavezna polja i linkove.');return;}const slug=this.form.controls.slug.value||'';if(this.originalStatus==='published'&&this.originalSlug&&slug&&slug!==this.originalSlug&&!window.confirm('Promena sluga moze prekinuti postojece linkove. Nastaviti?'))return;this.isSaving.set(true);this.errorMessage.set('');const id=this.itemId();const request=id?this.cms.update<Record<string,unknown>>('artists',id,this.payload()):this.cms.create<Record<string,unknown>>('artists',this.payload());request.subscribe({next:({item})=>{this.notifications.success('Profil umetnika je sacuvan.');this.form.markAsPristine();const savedId=this.idOf(item);if(!id&&savedId)this.router.navigate(['/admin/artists',savedId,'edit']);else this.patchArtist(item);},error:(error)=>{const message=error?.error?.message||'Cuvanje nije uspelo.';this.errorMessage.set(message);this.notifications.error(message);},complete:()=>this.isSaving.set(false)});}
  preview():void{const id=this.itemId();if(!id){this.notifications.info('Prvo sacuvajte nacrt.');return;}window.open(`/admin/artists/${id}/preview?lang=${this.activeLanguage()}`,'_blank','noopener');}
  updateImage(selection:MediaSelectionResult):void{this.imageSelection.set(selection.items.length?selection.items:selection.ids);this.form.controls.image.setValue(selection.ids[0]||'');this.form.controls.image.markAsDirty();}
  payload():Record<string,unknown>{const raw=this.form.getRawValue();return{...raw,image:raw.image||null,publishedAt:raw.publishedAt?new Date(raw.publishedAt).toISOString():undefined,galleryItems:(raw.galleryItems||[]).map((item,index)=>({...item,media:this.idOf(item.media),displayOrder:index})),links:this.array(raw.links).filter((item)=>item['label']&&item['url']).map((item,index)=>({...item,displayOrder:index}))};}
  private linkGroup(value:Record<string,unknown>,index:number){const en=this.object(this.object(value['translations'])['en']);return this.fb.group({label:[String(value['label']||''),Validators.required],url:[String(value['url']||''),[Validators.required,Validators.pattern(/^https?:\/\//i)]],type:[String(value['type']||'other')],translations:this.fb.group({en:this.fb.group({label:[String(en['label']||'')]})}),displayOrder:[index]});}
  private galleryValue(item:Record<string,unknown>):GalleryItemInput[]{const structured=this.array(item['galleryItems']);if(structured.length)return structured.map((entry,index)=>({media:entry['media'] as unknown as MediaSelectionValue,caption:String(entry['caption']||''),credit:String(entry['credit']||''),altText:String(entry['altText']||''),translations:this.object(entry['translations']) as GalleryItemInput['translations'],displayOrder:Number(entry['displayOrder']??index)}));return this.array(item['gallery']).map((media,index)=>({media:media as unknown as MediaSelectionValue,caption:'',credit:'',altText:'',displayOrder:index}));}
  private pairs(value:unknown):Array<{value:string;label:string}>{return this.array(value).map((item)=>({value:String(item['value']||''),label:String(item['label']||item['value']||'')}));}
  private idOf(value:unknown):string{if(!value)return'';if(typeof value==='string')return value;const item=this.object(value);return String(item['_id']||item['id']||'');}private object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};}private array(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.map((item)=>this.object(item)):[];}private strings(value:unknown):string[]{return Array.isArray(value)?value.map(String):[];}private dateTime(value:unknown):string{if(!value)return'';const date=new Date(String(value));const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
}
