import { CommonModule } from '@angular/common';
import { Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { EMPTY, Observable, catchError, combineLatest, distinctUntilChanged, finalize, map, switchMap, tap } from 'rxjs';

import { conditionLabel, costumeGenderLabel, propTypeLabel } from '../../../core/models/phase6a-labels';
import { CostumeItem, Phase6AItemResponse, PropScenographyItem } from '../../../core/models/phase6a.models';
import { PublicGalleryItem, PublicProduction, PublicSiteSettings } from '../../../core/models/public.models';
import { PublicApiService } from '../../../core/services/public-api.service';
import { PublicLocaleService } from '../../../core/services/public-locale.service';
import { PublicGalleryLightboxComponent } from '../../components/public-gallery-lightbox/public-gallery-lightbox.component';
import { PublicI18nService } from '../../i18n/public-i18n.service';
import { PublicTranslatePipe } from '../../i18n/public-translate.pipe';

@Component({selector:'app-public-fundus-detail',standalone:true,imports:[CommonModule,RouterLink,PublicGalleryLightboxComponent,PublicTranslatePipe],templateUrl:'./public-fundus-detail-view.html',styleUrl:'./public-fundus-detail-view.scss'})
export class PublicFundusDetailComponent implements OnInit {
  private readonly route=inject(ActivatedRoute);private readonly destroyRef=inject(DestroyRef);private readonly i18n=inject(PublicI18nService);readonly api=inject(PublicApiService);readonly locale=inject(PublicLocaleService);readonly item=signal<CostumeItem|PropScenographyItem|null>(null);readonly settings=signal<PublicSiteSettings|null>(null);readonly loading=signal(true);readonly error=signal('');readonly lightbox=signal<PublicGalleryItem[]|null>(null);readonly kind=signal<'costume'|'prop'>('costume');
  ngOnInit():void{this.api.getSiteSettings().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>this.settings.set(r.item)});combineLatest([this.route.paramMap,this.route.data]).pipe(map(([params,data])=>({slug:params.get('slug')||'',kind:(data['kind']==='prop'?'prop':'costume')as'costume'|'prop'})),distinctUntilChanged((a,b)=>a.slug===b.slug&&a.kind===b.kind),tap(({kind})=>{this.kind.set(kind);this.loading.set(true);this.error.set('');this.item.set(null);this.lightbox.set(null);window.scrollTo({top:0,behavior:'auto'});}),switchMap(({slug,kind})=>{const request=(kind==='costume'?this.api.getCostume(slug):this.api.getPropScenography(slug))as Observable<Phase6AItemResponse<CostumeItem|PropScenographyItem>>;return request.pipe(catchError(e=>{this.error.set(e?.error?.message||this.i18n.t('fundus.notFound'));return EMPTY;}),finalize(()=>this.loading.set(false)));}),takeUntilDestroyed(this.destroyRef)).subscribe(r=>{this.item.set(r.item);const srBase=this.kind()==='costume'?'/fundusi/kostimi':'/fundusi/rekviziti-scenografija';const enBase=this.kind()==='costume'?'/en/fundus/costumes':'/en/fundus/props-scenography';this.locale.registerPageLinks({sr:`${srBase}/${r.item.slugs?.sr||r.item.slug}`,en:r.item.slugs?.en?`${enBase}/${r.item.slugs.en}`:'/en/fundus'});});}
  isCostume(value:CostumeItem|PropScenographyItem):value is CostumeItem{return 'gender'in value;} image(value:unknown):string{return this.api.mediaUrl(value)||'/madlenianum/logo.png';} condition(value:string):string{return conditionLabel(value,this.locale.current());} gender(value:string):string{return costumeGenderLabel(value,this.locale.current());} type(value:string):string{return propTypeLabel(value,this.locale.current());} sectionLabel():string{return this.kind()==='costume'?this.i18n.t('fundus.costumes'):this.i18n.t('fundus.props');} relatedProductionImage(production:PublicProduction):string{return this.api.mediaUrl(production.poster)||'/madlenianum/logo.png';} contactPhone():string{return this.settings()?.fundusContact?.phone||this.settings()?.contact?.phones?.[0]||'';} contactEmail():string{return this.settings()?.fundusContact?.email||this.settings()?.contact?.generalEmail||'';} openGallery(index=0):void{const gallery=this.item()?.galleryItems||[];if(!gallery.length)return;this.lightbox.set([...gallery.slice(index),...gallery.slice(0,index)]);}
}
